version: '3'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
        ports:
        - 9200:9200
        volumes:
            - es_data:/data
    go-grpc-server:
        build: .
        command: ["go", "run", "main.go"]
        restart: 'on-failure'
        volumes:
        - .:/go/src/app
        ports:
        - "10001:10001"
        depends_on:
        - elasticsearch
    go-grpc-client:
        build: .
        command: ["go", "run", "main.go"]
        restart: 'on-failure'
        volumes:
            - .:/go/src/app
volumes:
    es_data: