version: '3'
services:
    elasticsearch:
        image: 'docker.elastic.co/elasticsearch/elasticsearch:6.3.2'
        restart: 'on-failure'
        ports:
            - 9200:9200
    go-grpc-server:
        build: ./go-grpc-server
        restart: 'on-failure'
        ports:
            - "10001:10001"
        environment:
            - ELASTICSEARCH_URL=http://elasticsearch:9200
        depends_on:
            - elasticsearch
    go-grpc-client:
        build: ./go-grpc-client
        restart: 'on-failure'
        environment: 
            - go-grpc-server=go-grpc-server
            - go-grpc-server-port=10001
        depends_on: 
            - go-grpc-server