version: '3.5'
services:
  search_api:
    container_name: 'search_api'
    build: ./search-api
    restart: 'on-failure'
    ports:
      - '8080:8080'
    depends_on:
      - elasticsearch
  elasticsearch:
    container_name: 'elasticsearch'
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.3.2'
    ports:
      - '9200:9200'
    volumes:
      - es_data:/data 
  kibana:
      image: docker.elastic.co/kibana/kibana:6.3.2
      ports:
          - "5601:5601"
      depends_on:
          - elasticsearch
volumes:
  es_data: