version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres-dev
      POSTGRES_PASSWORD: s3cr3tp4ssw0rd
    ports:
      - 5432:5432
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    ports:
      - 9200:9200
  app:
    build: .
    command: ["go", "run", "main.go"]
    volumes:
      - .:/go/src/app
    ports:
      - "80:8080"
    depends_on:
      - db
      - elasticsearch
    links:
      - db
      - elasticsearch